/* In data.js we are going to define a data and the data 
is object in object we are going to define productarray using [] */
const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Fit',
            category: 'Shirts',
            image: '/image/p1.jpg',
            price: 300,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'High quality product',
        },
        {
            _id: '2',
            name: 'Nike Slim Fit',
            category: 'Shirts',
            image: '/image/p2.jpg',
            price: 400,
            countInStock: 1,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 5,
            description: 'High quality product',
        },
        {
            _id: '3',
            name: 'Nike Slim Fit',
            category: 'Shirts',
            image: '/image/p3.jpg',
            price: 500,
            countInStock: 0,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 3,
            description: 'High quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Fit',
            category: 'Shirts',
            image: '/image/p1.jpg',
            price: 600,
            countInStock: 20,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 7,
            description: 'High quality product',
        },
        {
            _id: '5',
            name: 'Nike Slim Fit',
            category: 'Shirts',
            image: '/image/p2.jpg',
            price: 700,
            countInStock: 5,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 12,
            description: 'High quality product',
        },
        {
            _id: '6',
            name: 'Nike Slim Fit',
            category: 'Shirts',
            image: '/image/p3.jpg',
            price: 800,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            description: 'High quality product',
        },
    ],
};

export default data;
